### ISSUE TITLE
Error when using d3-geo-projection with d3 4.1?

### ISSUE THREAD

**Issue by iandees** [d3/d3-geo-projection#44]
I'm trying to use d3-geo-projection from within a Node.js context (to [render some OSM data](https://twitter.com/iandees/status/749073312613969920)). I followed the instructions in the readme:

```
npm install d3 d3-geo-projection
```

and in my javascript:

```javascript
var Canvas = require("canvas"),
    d3 = require("d3"),
    topojson = require("topojson"),
    rw = require("rw"),
    world = require("./world-110m.json");
require("d3-geo-projection")(d3);
```

But when I try to run this, I get:

```
undefined:4
  d3.geo.project = function(object, projection) {
                 ^

TypeError: Cannot set property 'project' of undefined
    at eval (eval at <anonymous> (/Users/iandees/Downloads/d32video/node_modules/d3-geo-projection/index.js:4:18), <anonymous>:4:18)
    at eval (eval at <anonymous> (/Users/iandees/Downloads/d32video/node_modules/d3-geo-projection/index.js:4:18), <anonymous>:1916:3)
    at Object.<anonymous> (/Users/iandees/Downloads/d32video/draw.js:9:29)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3
```

**Comment by Fil** [comment]
Same. I suspect it's because this module isn't finished porting to d3v4 (#32).

**Comment by iandees** [comment]
Ah, I was just looking at that and should have connected the dots. I'll try running an older version of d3 for now. Thanks!

**Comment by mbostock** [comment]
Yes. We are porting this library to 4.0 now, but in the interim 3.x is required. Sorry!
