### ISSUE TITLE
Error: "toString()" failed

### ISSUE THREAD

**Issue by jgerardsimcock** [d3/d3-geo-projection#94]
I have a .shp file of the whole globe. I tried using geostitch since I have a full globe and I get a similar error. Not sure if I am missing a js dependency or something else. 

`shp2json ~/data/mapping/world-combo-new/betas.shp -o world.json` #this works

`geoproject 'd3.geo.cylindricalEqualArea().parallel(37.5).fitSize([960,960],d)' < world.json > world-mercator.json`

```buffer.js:495 throw new Error('"toString()" failed');

Error: "toString()" failed
    at Buffer.toString (buffer.js:495:11)
    at Object.parse (native)
    at ReadStream.<anonymous> (/usr/local/lib/node_modules/d3-geo-projection/bin/read.js:13:48)
    at emitNone (events.js:91:20)
    at ReadStream.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)```

**Comment by mbostock** [comment]
If your JSON input is greater than (I believe) 256M, then *buffer*.toString fails trying to parse the input; see nodejs/node#3175. Your best bet is probably to use newline-delimited JSON as input, such that each feature is put on a separate line. Like so:

```
shp2json -n world.shp | geoproject -n 'd3.geo.cylindricalEqualArea().parallel(37.5).fitSize([960,960],d)' -o world-mercator.ndjson
```

Alternatively these tools could be rewritten to use a streaming JSON parser such as [JSONStream](https://github.com/dominictarr/JSONStream), but I have no plans to do this in the near future.
